### ISSUE TITLE
GPIO Pin assignment and error message

### ISSUE THREAD

**Issue by pgs32** [Switchdoctorstu/StuPiMo#1]
Hi

I am hoping you can help, I am inexperienced with c and GPIO hardware but am keen to learn and complete this project. 

I am using a Raspberry Pi model B Rev 2 running an up to date copy of Raspbian, but needed to change some of the GPIO pins that are used, namely 0 to 8, 1 to 9, 5 to 10 and 6 to 11.

Can you tell me where I change the GPIO numbers in the StuPiMo file, a simple example would be very helpful, can I edit the compiled file or do the changes need to be made before the file is compiled?

When I run the file ./StuPiMo I get the following output in terminal;

pi@relayalexa:~/stu $ ./StuPiMo
Getting Local Interface IP Addresses
1: lo
	 127.0.0.1
2: eth0
	 192.168.0.71
Found 2 interfaces 
Address:127.0.0.1
Address:192.168.0.71
Root: Spawning "Socket 1" on 192.168.0.71 port:43450 gpio pin:0
Root: - the process identifier (pid) of child: 0 is: 1710
Child 0: Starting "Socket 1" on port 43450
Socket 1: Listening on port:43450...
Root: Spawning "Socket 2" on 192.168.0.71 port:43451 gpio pin:1
Root: - the process identifier (pid) of child: 1 is: 1711
Child 1: Starting "Socket 2" on port 43451
Socket 2: Listening on port:43451...
Root: Spawning "Socket 3" on 192.168.0.71 port:43452 gpio pin:2
Root: - the process identifier (pid) of child: 2 is: 1712
Child 2: Starting "Socket 3" on port 43452
Socket 3: Listening on port:43452...
Root: Spawning "Socket 4" on 192.168.0.71 port:43453 gpio pin:3
Root: - the process identifier (pid) of child: 3 is: 1713
Child 3: Starting "Socket 4" on port 43453
Socket 4: Listening on port:43453...
Root: Spawning "Socket 5" on 192.168.0.71 port:43454 gpio pin:4
Root: - the process identifier (pid) of child: 4 is: 1714
Child 4: Starting "Socket 5" on port 43454
Socket 5: Listening on port:43454...
Root: Spawning "Socket 6" on 192.168.0.71 port:43455 gpio pin:5
Root: - the process identifier (pid) of child: 5 is: 1715
Child 5: Starting "Socket 6" on port 43455
Socket 6: Listening on port:43455...
Root: Spawning "Socket 7" on 192.168.0.71 port:43456 gpio pin:6
Root: - the process identifier (pid) of child: 6 is: 1716
Child 6: Starting "Socket 7" on port 43456
Socket 7: Listening on port:43456...
Root: Spawning "Socket 8" on 192.168.0.71 port:43457 gpio pin:7
Root: - the process identifier (pid) of child: 7 is: 1717
Child 7: Starting "Socket 8" on port 43457
Socket 8: Listening on port:43457...
Root: All devices started
Webserver: Listening on port:5353...
Socket Created
SSDP: Address set
SSDP: Socket Bound
setsockopt error
SSDP RESPONDER EXITED!

Webserver: Received Web Post request:
POST /socket HTTP/1.1
Host: 192.168.0.71:5353
Connection: keep-alive
Content-Length: 9
Cache-Control: max-age=0
Origin: http://192.168.0.71:5353
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
Save-Data: on
User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; CMR-AL19) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: http://192.168.0.71:5353/socket
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

toggle7=0
Toggle state of pin: 7 GPIO: 7 
Socket: 0  State:1
Socket: 1  State:1
Socket: 2  State:1
Socket: 3  State:1
Socket: 4  State:1
Socket: 5  State:1
Socket: 6  State:1
Socket: 7  State:1
Webserver: Webpage request:
Webserver: Response sent

I can see the web server on port 5353 and when I change the state of the relay on the web page the state also changes in the terminal window. However physically the relay does not change state (even on the unchanged GPIO pins in the code, i.e. GPIO pins 2, 3, 4 and 7) and I get an error message "setsockopt error"? 

Any help or advice would be much appreciated. 

Many thanks 

Simon

**Comment by Switchdoctorstu** [comment]
Hi Simon, Sorry it's been a while - the Github notification went to spam...

The GPIO pin numbers are set at around line 871:
They're store in the array gpioPin[]
I cheated a little in that they just increment from 0 to NUMDEVICES

for (i = 0; i < NUMDEVICES; i++) {

		port[i] = PORTBASE + i;
		gpioPin[i] = i;
		pinMode(i, OUTPUT);			// set our pin to output
	}

You could add a base to shift them:
gpioPin[i] = i+8;

or delete the line and load them manually just after the loop:
gpioPin[0] =8;
gpioPin[1] =12;
gpioPin[2] =7;
gpioPin[3] =2;
etc

**Comment by Switchdoctorstu** [comment]
WRt the "setsockopt error" - have you set your network interface to promiscous mode?

If not you need to run the command:
sudo ifconfig eth0 promisc

otherwise the interface can't see UDP packets.
You can set this permanently by adding the line above to your
/etc/rc.local file

i.e. 
sudo nano /etc/rc.local

and add the line

**Comment by Switchdoctorstu** [comment]
PS, very sorry to have missled you , if you use the StuPiMo.c as source (not StuPiMoDevice) i've fixed the issue with toggling the pins, i'd inverted it to drive the relays correctly but that spooked the toggle, fixed now.
