### ISSUE TITLE
Possible to switch for n seconds?

### ISSUE THREAD

**Issue by wodgey** [Switchdoctorstu/StuPiMo#2]
I'm looking to implement a couple of Alexa controllable relays into my daughter's stair lift, so she can have Alexa send the lift up\down stairs, using voice control. How easy would this be to have a relay operate for 20 seconds (or however long it takes for the lift to fully traverse)?

**Comment by Switchdoctorstu** [comment]
Hiya,  
Whilst you could code a simple delay(20 secs) into the routine by say passing an additional parameter to the forked processes; being an engineer i'd approach it a different way; 
If you're attaching relays to the motor then i'd take a connection from the up/down limit-switch on the chair to one of the gpio pins on the RPi and use that to reset the relay. Again i'd maybe pass the number of a gpio pin to 'watch' to the forked process. If it sees this pin go low say it would set the relay state to off.

**Comment by wodgey** [comment]
Ah ha. Thank you for prodding me into looking at things differently. Yes. Nice idea of utilising the reed switches that are already in situ.

However, I see that there are already a commercial product that does exactly what I require, with far less cost\effort. The "inching" feature on a 2ch relay is perfect for my use case and easily integrated with both Alexa and Google home.
