### ISSUE TITLE
non-inverted control

### ISSUE THREAD

**Issue by andyrobik** [Switchdoctorstu/StuPiMo#3]
Hi, I'd like to adjust the code for HIGH level triggered relays. Already tried to swap the HIGH for LOW and vice versa in `digitalWrite(pin, ...);` lines, but without success. Thank you for this code.

**Comment by Switchdoctorstu** [comment]
It should be a case of swapping the code around line 384:
	if (state == 0x30) {
								device_state = 0;

								digitalWrite(pin, LOW);			// Relay card is NOT inverted
								printf("%s:Binary State Set to 0\n", devicename);
							}
							if (state == 0x31) {
								device_state = 1;

								digitalWrite(pin, HIGH);	// Relay card is NOT inverted
								printf("%s:Binary State Set to 1\n", devicename);
							}

**Comment by andyrobik** [comment]
that is exactly what i tried + swapped the _digitalWrite(pin, ..._ around line 745
unfortunately alexa tells there is an error. When i revert back to the inverted logic binary it works again ...

**Comment by Switchdoctorstu** [comment]
think i've found it; around line 337:

I added a few lines of code to cater for the inverted relays - if you comment around this block:
/*
if (device_state == 0) {
							device_state = 1;
						}
						else {
							device_state = 0;
						}
*/

Then it should report the correct state back to the controller when it asks *getstate.

**Comment by andyrobik** [comment]
That was it, thank you plenty. It would be great to have a boolean switch in the code s config area to take care of this.
