### ISSUE TITLE
Echo discovery

### ISSUE THREAD

**Issue by brysenn** [Switchdoctorstu/StuPiMo#4]
I've built this project and have been using it very successfully since October but recently the Echo/Alexa can no longer find the Raspberry PI.  The web controller is working and the relay is still working.  It's only the connection with the Echo that isn't working.  Any help would be MUCH appreciated!

**Comment by Switchdoctorstu** [comment]
Long time to reply but i got back to this project recently and re-built a PI W using the code ok.

Advice i'd try is to re-name the device friendly names and get alexa to re-dsicover them.

**Comment by Switchdoctorstu** [comment]
Resolved
