### ISSUE TITLE
Changing on/off commands

### ISSUE THREAD

**Issue by Llednarr** [Switchdoctorstu/StuPiMo#5]
Is there a way to change on/off commands to a single word/trigger?

I am using this script with a physical switch as backup for when it cannot be run for whatever reason (no internet or damaged relay). My issue is that, if the switch/socket is off and I use the physical switch to turn it on, the raspberry pi still sees it as off, and I have to say "turn x on" turn it off and vice versa.

Not a big deal for myself, but it may be confusing for my mom. So hoping there's someone with a solution out there.

**Comment by Switchdoctorstu** [comment]
I've had a think about this and it's harder than it looks as the current code blocks when it's waiting for a packet.
I could think of a way that the master loop monitors some extra GPIO pins with overide switches on them. The spawned handlers could monitor the GPIO status and report that back.

As an electrical work-around; if you wire this relay and your device like a heater control, a master SPST on/off switch then a SPDT auto/on switch that overrides the Pi Relay - it may give you the override control you need.
